### ISSUE TITLE
Completion RoadMap

### ISSUE THREAD

**Issue by laginha87** [crystal-lang-tools/scry#66]
Hi all, this issue is a compilation of features I think we can add to the completion part of scry.
Open to suggestions.

# Overview

- [ ] Load classes from libs
- [ ] Add module function completion

## Literal object declarations
- [ ] Add string literal completion
- [ ] Add array literal method completion
- [ ] Add hash literal method completion

- [ ] Support generic method completion
- [ ] Add chain method completion
- [ ] Add inherited instance methods completion
- [ ] Add inherited class methods completion
- [ ] Add json mappings completion

## Requires identifying context:
- [ ] Add symbol completion
- [ ] Add overloading auto complete
- [ ] Add overriding autocompletion when definining a new method
- [ ] Add module function completion in module context
- [ ] Add classname completion with module namespace
- [ ] Add top level classname completion.
- [ ] Add top level module completion

# Descriptions
## Load classes from libs
Any class defined under  libs/ isn't used, this is because the requires aren't looked up properly when loading the requires

## Add Module function completion
Right now we identify class methods but don't identify module functions. For example: ```Kemal.r``` should complete with run.

# Literal object declarations
This section is for when we have situations like ```a = [] of String``` it should identify a as ```Array(String)```.

## Add string literal completion
```crystal
 a = ""
```
should identify a as String.

## Add array literal method completion
```crystal
 a = [1,2,3]
 a = [] of String
```
Should identify as Array(String, String).

## Add hash literal method completion
```crystal
a = {
    "" => ""
}

a = {} of String => String
```
Should identify as Hash(String, String)

##  Support generic method completion

```a = [] of String; a.map(&.)``` should complete with string methods.

## Add chain method completion
``` a.method_a.method_b.``` should be able to give some completion hints (This needs methods to define the return type or we need to find away to guess tha too.)

## Add inherited instance methods completion
When suggesting completion on an object it should also include instance methods from the classes it inherits from.

## Add inherited class methods completion
When suggesting completion on a class  it should also include class methods from the classes it inherits from.

## Add included methods completion
When suggesting completion on an object  it should also include methods inherited from included modules.

## Add json mappings completion
I have no idea how to handle completion on methods defined by macros, so we could add special cases for json mappings.

## Requires identifying context:
This set of features needs the completion code to identify which class or module the cursor is on.

TODO Fill out this section.
